# Default Setting

spring:
  application:
    name: oring_server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=true&requireSSL=true&verifyServerCertificate=false
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
  main:
    allow-bean-definition-overriding: true

my:
  token: ${MY_SECRET_KEY}

server:
  servlet:
    context-path: /api
